config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  def index
    @posts = Post.all

    if params[:fetch_images]
      response = Faraday.get("http://shibe.online/api/shibes?count=5&urls=true&httpsUrls=true")
      @image = JSON.parse(response.body).first
    end

  end

  def show
  end
  
  def new
    @post = Post.new
    response = Faraday.get("http://shibe.online/api/shibes?count=5&urls=true&httpsUrls=true")
    @image = JSON.parse(response.body).first

    if params[:fetch_images]
      response = Faraday.get("http://shibe.online/api/shibes?count=5&urls=true&httpsUrls=true")
      @image = JSON.parse(response.body).first
    end
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post, notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: "Post was successfully destroyed.", status: :see_other
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="pastel" > 
  <head>
    <title>SampleRails7</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, class: "contents") do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :大喜利画像 %><br>

    <% if post.image.present?  %>
      <%= image_tag post.image, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2" %>
    <% else %>
      <%= link_to "画像を再取得", new_post_path(fetch_images: true), method: :get, class: 'btn btn-primary' %>
      <img src="<%= @image %>" alt="Shibe Image" width="500", class="block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2">
    <% end %>
  </div>
  <div class="my-5">
    <%= form.label :タイトル %>
    <%= form.text_area :title, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :内容 %>
    <%= form.text_area :body, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <%= form.hidden_field :image, value: @image %>

  <div class="inline my-5">
    <%= form.submit "投稿する", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">

  <div class="card w-96 bg-slate-100 p-3 m-4">
    <div class="card-body">
      <img src="<%= post.image %>" alt="Shibe Image" width="300">
      <h2 class="card-title"><%= post.title %></h2>
      <p><%= post.body %></p>
      <p>
        <%= link_to "詳細", post, class: "rounded-lg py-3 px-5 bg-sky-500 inline-block font-medium" %>
        <%= link_to "編集", edit_post_path(post), class: "rounded-lg py-3 ml-2 px-5 bg-orange-600 inline-block font-medium" %>
      <p>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">編集</h1>

  <%= render "form", post: @post %>

  <%= link_to "詳細", @post, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "戻る", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <%= link_to "投稿する", new_post_path, class: "rounded-lg py-3 px-5 m-3 bg-sky-500 inline-block font-medium" %>

  <div class="flex justify-between items-center p-3">
    <h1 class="font-bold text-4xl">投稿一覧</h1>
  </div>

  <%= render @posts %>  
</div>

app/views/posts/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">新規投稿</h1>

  <%= render "form", post: @post %>

  <%= link_to "戻る", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/posts/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @post %>

    <%= link_to "編集", edit_post_path(@post), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "削除", post_path(@post), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "戻る", posts_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>